<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-P5OMGMR" failures="1" tests="4" name="Test" time="51.616" errors="0" timestamp="2023-10-01T13:05:06 EET">
  <testcase classname="com.qa.tests.LoginTests" name="emptyUserName" time="6.24"/>
  <testcase classname="com.qa.tests.LoginTests" name="invalidPass" time="3.893"/>
  <testcase classname="com.qa.tests.LoginTests" name="invalidUserName" time="12.731">
    <failure type="java.lang.AssertionError" message="expected [Username and password do not match any user in this service.] but found [Username and password do not match any user in this service.fdf]">
      <![CDATA[java.lang.AssertionError: expected [Username and password do not match any user in this service.] but found [Username and password do not match any user in this service.fdf]
at com.qa.tests.LoginTests.invalidUserName(LoginTests.java:64)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- invalidUserName -->
  <testcase classname="com.qa.tests.LoginTests" name="successfullyLogin" time="4.614"/>
</testsuite> <!-- Test -->
