<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-P5OMGMR" failures="1" tests="4" name="com.qa.tests.LoginTests" time="33.975" errors="0" timestamp="2023-10-01T13:05:06 EET" skipped="0">
  <testcase classname="com.qa.tests.LoginTests" name="emptyUserName" time="7.660"/>
  <system-out/>
  <testcase classname="com.qa.tests.LoginTests" name="invalidUserName" time="14.262">
    <failure message="expected [Username and password do not match any user in this service.] but found [Username and password do not match any user in this service.fdf]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Username and password do not match any user in this service.] but found [Username and password do not match any user in this service.fdf]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at com.qa.tests.LoginTests.invalidUserName(LoginTests.java:64)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
]]>
    </failure>
  </testcase> <!-- invalidUserName -->
  <system-out>
    <![CDATA[This is the sample screenshot
<a href='C:\Users\Khaled Mohsen\IdeaProjects\TDDAppiumFramWorkPOM\screenshot\Android_Any Device version_Any Device name_\2023-10-01-13-04-14\LoginTests\invalidUserName.png'> <img src='C:\Users\Khaled Mohsen\IdeaProjects\TDDAppiumFramWorkPOM\screenshot\Android_Any Device version_Any Device name_\2023-10-01-13-04-14\LoginTests\invalidUserName.png' height='100' width='100'/> </a>]]>
  </system-out>
  <testcase classname="com.qa.tests.LoginTests" name="invalidPass" time="5.250"/>
  <system-out/>
  <testcase classname="com.qa.tests.LoginTests" name="successfullyLogin" time="6.803"/>
  <system-out/>
</testsuite> <!-- com.qa.tests.LoginTests -->
